// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrelkcxrvsilnxzgizul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZWxrY3hydnNpbG54emdpenVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzA4NzIsImV4cCI6MjA2MzYwNjg3Mn0.kUXnoovSVjbPMj-1ddE_yjLSuq4cBGKrrMRVo433J_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);